# Generated by Django 4.1 on 2022-11-10 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateTimeField(verbose_name='date created')),
                ('period', models.CharField(choices=[('D', 'Once a day'), ('W', 'Once a week'), ('M', 'Once a month'), ('Y', 'Once a year'), ('O', 'Once'), ('C', 'Custom')], default='W', max_length=1)),
                ('condition', models.CharField(choices=[('A', 'Awful'), ('B', 'Bad'), ('N', 'Normal'), ('G', 'Good'), ('E', 'Excellent')], default='N', max_length=1)),
                ('effort', models.CharField(choices=[('E', 'Easy'), ('N', 'Normal'), ('H', 'Hard')], default='N', max_length=1)),
                ('status', models.BooleanField(verbose_name='chore status')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RoomsChores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaning_app.chore')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaning_app.room')),
            ],
        ),
    ]
