# Generated by Django 4.1 on 2022-11-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cleaning_app.room'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RoomsChores',
        ),
    ]
