# Generated by Django 4.1 on 2022-12-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0002_chore_room_delete_roomschores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_chores', to='cleaning_app.room'),
        ),
    ]
