# Generated by Django 4.1 on 2022-12-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0006_room_family_slave_family_alter_chore_slave'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(default='#519c3f', max_length=25),
            preserve_default=False,
        ),
    ]
