# Generated by Django 4.1 on 2022-12-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0008_alter_chore_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='condition',
        ),
        migrations.AddField(
            model_name='chore',
            name='period_type',
            field=models.CharField(choices=[('D', 'days'), ('W', 'weeks'), ('M', 'months'), ('Y', 'years'), ('O', 'once')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='chore',
            name='period',
            field=models.PositiveIntegerField(null=True, verbose_name='period count'),
        ),
    ]
