# Generated by Django 4.1 on 2023-01-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0010_alter_slave_family_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='cleaning_app.slave'),
        ),
    ]
