# Generated by Django 4.1 on 2023-01-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0011_alter_invite_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='is_join_request',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
