# Generated by Django 4.1 on 2023-01-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0012_alter_invite_receiver_alter_invite_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
