# Generated by Django 4.1 on 2023-01-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0012_invite_is_join_request_alter_invite_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='slave',
            name='is_admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
