# Generated by Django 4.1 on 2023-01-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0013_slave_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slave',
            name='is_admin',
            field=models.BooleanField(null=True),
        ),
    ]
